plugins {
    id 'java'
    id 'application'
    id 'org.sonarqube' version '4.4.1.3373'  // SonarQube plugin
}

group = 'com.saiteja.helloworld'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

application {
    mainClass = 'com.saiteja.helloworld.App'
}
test {
    useJUnitPlatform()
}
jar {
    archiveBaseName.set("hello-world")
    archiveVersion.set("1.0.0-SNAPSHOT")
}
